/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentPickerSheet: typeof import('./components/chat/AgentPickerSheet.vue')['default']
    ChatBubble: typeof import('./components/chat/ChatBubble.vue')['default']
    ChatComposer: typeof import('./components/chat/ChatComposer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionsDrawer: typeof import('./components/chat/SessionsDrawer.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
